version: "3.6"

services:
  redis:
    image: redis:latest
    container_name: redis
    command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
    restart: always
    networks:
      - "traefik-network"

networks:
  traefik-network:
    external: true
