version: "3.7"

services:
      
  wwordpress:
    image: wordpress:latest
    restart: always
    env_file:
      - .env
    environment:
      TZ: Asia/Jakarta
      # Connect WordPress to the database
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.domain.com`)"
      - "traefik.http.routers.wordpress.entrypoints=web"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.routers.wordpress.tls.certresolver=letsencrypt"
    volumes:
      - ./data:/var/www/html
    networks:
      - "traefik-network"

networks:
  traefik-network:
    external: true